const STATUS_ORDER_REQUEST_NOTHING = 1000;
const STATUS_ORDER_REQUEST_WAITING = 0;
const STATUS_ORDER_REQUEST_ACCEPTED = 1;
const STATUS_ORDER_REQUEST_CANCELED = 2;

export { STATUS_ORDER_REQUEST_NOTHING, STATUS_ORDER_REQUEST_ACCEPTED, STATUS_ORDER_REQUEST_WAITING, STATUS_ORDER_REQUEST_CANCELED };